### ISSUE TITLE
게시판 CRUD

### ISSUE THREAD

**Issue by amm0124** [amm0124/2024-2-database-termproject#17]
### ✏️ Describe

게시판 CRUD(1)

### ✅ TO-DO

게시판 Create(post)
- [x] free, tip 게시판 
- [x] matching 게시판 ,  tournament 게시판 
- [ ] 공지(홍보)게시판 (Promotion) 게시판 
 

게시판 read(get)
- [x] free, tip 게시판 
- [ ] matching 게시판 ,  tournament 게시판 
- [ ] 공지(홍보)게시판 (Promotion) 게시판 

### 🙋🏻 More

게시판 CRUD
