### ISSUE TITLE
게시판 CRUD(2)

### ISSUE THREAD

**Issue by amm0124** [amm0124/2024-2-database-termproject#18]
### ✏️ Describe

게시판 CRUD(2)

### ✅ TO-DO

게시판 Update(PUT)
- [ ] free, tip 게시판 
- [ ] matching 게시판 
- [ ] 공지(홍보)게시판 (Promotion) 게시판 
- [ ] tournament 게시판 

게시판 delete
- [ ] free, tip 게시판 
- [ ] matching 게시판 
- [ ] 공지(홍보)게시판 (Promotion) 게시판 
- [ ] tournament 게시판 

### 🙋🏻 More

게시판 Update(PUT)
- [ ] free, tip 게시판 
- [ ] matching 게시판 
- [ ] 공지(홍보)게시판 (Promotion) 게시판 
- [ ] tournament 게시판 

게시판 delete
- [ ] free, tip 게시판 
- [ ] matching 게시판 
- [ ] 공지(홍보)게시판 (Promotion) 게시판 
- [ ] tournament 게시판
