### ISSUE TITLE
회원가입시 memberprofile도 같이 입력받도록 변경 + 회원 crud

### ISSUE THREAD

**Issue by amm0124** [amm0124/2024-2-database-termproject#23]
### ✏️ Describe

회원가입시 memberprofile도 같이 입력받도록 변경 + 쿼리 최적화

### ✅ TO-DO

회원가입시 memberprofile도 같이 입력받도록 변경
- [x] 이 과정에서 nullexception 해결 
- [x] security context에서 정보 가져 올 때 fetch join 사용하도록 

### 🙋🏻 More

회원가입시 memberprofile도 같이 입력받도록 변경
- [x] 이 과정에서 nullexception 해결

**Comment by amm0124** [comment]
수정 1:1관계에서 쿼리가 6번 나감 -> 고쳐보자 
```
    Hibernate: 
        select
            m1_0.id,
            m1_0.created_at,
            m1_0.email,
            m1_0.is_deleted,
            m1_0.is_verify,
            m1_0.member_profile_id,
            m1_0.password,
            m1_0.role,
            m1_0.updated_at 
        from
            member m1_0 
        where
            (
                m1_0.is_deleted = false
            ) 
            and m1_0.email=?
    Hibernate: 
        select
            mp1_0.id,
            mp1_0.address,
            mp1_0.address_detail,
            mp1_0.name,
            mp1_0.phone_number 
        from
            member_profile mp1_0 
        where
            mp1_0.id=?
    Hibernate: 
        select
            mp1_0.id,
            mp1_0.address,
            mp1_0.address_detail,
            mp1_0.name,
            mp1_0.phone_number 
        from
            member_profile mp1_0 
        where
            mp1_0.id=?
    Hibernate: 
        select
            m1_0.id,
            m1_0.created_at,
            m1_0.email,
            m1_0.is_deleted,
            m1_0.is_verify,
            mp1_0.id,
            mp1_0.address,
            mp1_0.address_detail,
            mp1_0.name,
            mp1_0.phone_number,
            m1_0.password,
            m1_0.role,
            m1_0.updated_at 
        from
            member m1_0 
        left join
            member_profile mp1_0 
                on mp1_0.id=m1_0.member_profile_id 
        where
            m1_0.id=? 
            and (
                m1_0.is_deleted = false
            )
    Hibernate: 
        update
            member 
        set
            email=?,
            is_deleted=?,
            is_verify=?,
            member_profile_id=?,
            password=?,
            role=?,
            updated_at=? 
        where
            id=?
    Hibernate: 
        update
            member 
        set
            email=?,
            is_deleted=?,
            is_verify=?,
            member_profile_id=?,
            password=?,
            role=?,
            updated_at=? 
        where
            id=?
```

**Comment by amm0124** [comment]
정보 조회할 때 
security Authentication principal에 member 객체를 넣는데 
이 때 일반 JPA 메서드 사용해서 조회함

이를 join fetch로 처리
![image](https://github.com/user-attachments/assets/b8f31f5f-88b0-41c1-91e5-04514a2236d4)

**Comment by amm0124** [comment]
이러면 
일단 정보 조회할 때는 query 2->1로 줄어든다
![image](https://github.com/user-attachments/assets/7e37f5f1-cd48-4ebe-bf86-052ee773641b)

**Comment by amm0124** [comment]
정보 수정할 때 쿼리가 5번 나감

``` 코드
public MemberResponse editMemberInfo(MemberEditRequest memberEditRequest){
        Member member = getMember();
        MemberProfile memberProfile = member.getMemberProfile();

        System.out.println("정보가져옴 --------");
        
        String password = null;
        if(memberEditRequest.password() != null){
           password = passwordEncoder.encode(memberEditRequest.password());
        }

        member.editMemberInfo(
                password
        );

        System.out.println("멤버수정 --------");
        
        memberProfile.editMemberProfile(memberEditRequest.name(),
                memberEditRequest.address(),
                memberEditRequest.addressDetail(),
                memberEditRequest.phoneNumber());


        System.out.println("멤버profile수정 --------");
        
        memberProfileRepository.save(memberProfile);

        System.out.println("profile save~");

        memberRepository.save(member);

        System.out.println("member save~");


        return MemberResponse.from(member);
    }

```

결과 
```
Hibernate: 
    select
        m1_0.id,
        m1_0.created_at,
        m1_0.email,
        m1_0.is_deleted,
        m1_0.is_verify,
        mp1_0.id,
        mp1_0.address,
        mp1_0.address_detail,
        mp1_0.name,
        mp1_0.phone_number,
        m1_0.password,
        m1_0.role,
        m1_0.updated_at 
    from
        member m1_0 
    left join
        member_profile mp1_0 
            on mp1_0.id=m1_0.member_profile_id 
    where
        (
            m1_0.is_deleted = false
        ) 
        and m1_0.email=?
정보가져옴 --------
멤버수정 --------
멤버profile수정 --------
Hibernate: 
    select
        mp1_0.id,
        mp1_0.address,
        mp1_0.address_detail,
        mp1_0.name,
        mp1_0.phone_number 
    from
        member_profile mp1_0 
    where
        mp1_0.id=?
profile save~
Hibernate: 
    select
        m1_0.id,
        m1_0.created_at,
        m1_0.email,
        m1_0.is_deleted,
        m1_0.is_verify,
        mp1_0.id,
        mp1_0.address,
        mp1_0.address_detail,
        mp1_0.name,
        mp1_0.phone_number,
        m1_0.password,
        m1_0.role,
        m1_0.updated_at 
    from
        member m1_0 
    left join
        member_profile mp1_0 
            on mp1_0.id=m1_0.member_profile_id 
    where
        m1_0.id=? 
        and (
            m1_0.is_deleted = false
        )
Hibernate: 
    update
        member 
    set
        email=?,
        is_deleted=?,
        is_verify=?,
        member_profile_id=?,
        password=?,
        role=?,
        updated_at=? 
    where
        id=?
member save~
정보가져옴 --------
멤버수정 --------
멤버profile수정 --------
profile save~
Hibernate: 
    update
        member 
    set
        email=?,
        is_deleted=?,
        is_verify=?,
        member_profile_id=?,
        password=?,
        role=?,
        updated_at=? 
    where
        id=?
member save~
```

메서드 자체가 2번 실행 된다

**Comment by amm0124** [comment]
디버깅 시작

결과 .. 2번 실행이 되길래 controller에서 2번 호출하고 있었음..
![image](https://github.com/user-attachments/assets/42a7ccb4-fa60-43b5-887f-0c5c17995ccb)

바뀌는 것이 없으니 두 번째 호출에선 쿼리가 한 번만 실행되는 것 
-> 영속성 컨텍스트와 비교해서 쿼리를 호출한다

**Comment by amm0124** [comment]
쿼리가 3번 정상적으로 호출 됨 -> 근데 
fetch join으로 2번 가져오는 거 1번으로 바꿨는데
update query도 2번에서 1번으로는 못 바꾸나?

**Comment by amm0124** [comment]
> Hibernate: 
>     select
>         m1_0.id,
>         m1_0.created_at,
>         m1_0.email,
>         m1_0.is_deleted,
>         m1_0.is_verify,
>         mp1_0.id,
>         mp1_0.address,
>         mp1_0.address_detail,
>         mp1_0.name,
>         mp1_0.phone_number,
>         m1_0.password,
>         m1_0.role,
>         m1_0.updated_at 
>     from
>         member m1_0 
>     left join
>         member_profile mp1_0 
>             on mp1_0.id=m1_0.member_profile_id 
>     where
>         (
>             m1_0.is_deleted = false
>         ) 
>         and m1_0.email=?
> 정보가져옴 --------
> 멤버수정 --------
> 멤버profile수정 --------
> Hibernate: 
>     select
>         mp1_0.id,
>         mp1_0.address,
>         mp1_0.address_detail,
>         mp1_0.name,
>         mp1_0.phone_number 
>     from
>         member_profile mp1_0 
>     where
>         mp1_0.id=?
> profile save~
> Hibernate: 
>     select
>         m1_0.id,
>         m1_0.created_at,
>         m1_0.email,
>         m1_0.is_deleted,
>         m1_0.is_verify,
>         mp1_0.id,
>         mp1_0.address,
>         mp1_0.address_detail,
>         mp1_0.name,
>         mp1_0.phone_number,
>         m1_0.password,
>         m1_0.role,
>         m1_0.updated_at 
>     from
>         member m1_0 
>     left join
>         member_profile mp1_0 
>             on mp1_0.id=m1_0.member_profile_id 
>     where
>         m1_0.id=? 
>         and (
>             m1_0.is_deleted = false
>         )
> Hibernate: 
>     update
>         member 
>     set
>         email=?,
>         is_deleted=?,
>         is_verify=?,
>         member_profile_id=?,
>         password=?,
>         role=?,
>         updated_at=? 
>     where
>         id=?
> member save~

gpt왈 이건 안 되는 거 같다 .. !

**Comment by amm0124** [comment]
그렇다면 null을 넣은 data를 update해보자!
![image](https://github.com/user-attachments/assets/0950c77c-572a-4ad6-a101-4cc95f9d50b8)

![image](https://github.com/user-attachments/assets/1945533b-a6f6-4497-844c-6c92f48da1f2)
