### ISSUE TITLE
매칭/대회 참여 api 

### ISSUE THREAD

**Issue by amm0124** [amm0124/2024-2-database-termproject#38]
### ✏️ Describe

매칭/대회 참여 api 
매칭,대회 참여 인원 상탯값 저장해야 함 -> 테이블 

### ✅ TO-DO

- [x] 매칭/대회 참여 api 
- [x] 상태 저장 테이블
- [x] 매칭 삭제
- [x] 대회 참여정보 수정
> N:M 문제를 중간 테이블 두어 해결

### 🙋🏻 More

N:M 문제를 중간 테이블 두어 해결
